### ISSUE TITLE
Bug fix in Class 37 practice lab

### ISSUE THREAD

**Issue by BillyBunn** [codefellows/seattle-javascript-401n13#4]
`player-form.js` has a `useEffect` that's causing an infinite render loop. Instead of `[data]`, it should have `[]` as its second argument.

**Line 22 in [`src/components/player-form.js`](https://github.com/codefellows/seattle-javascript-401n13/blob/master/curriculum/class-37/lab/starter-code/practice/src/components/player-form.js)**

**Comment by adrianhuebner** [comment]
Repo to be made private and archived, so closing issue
